Everything works enough to build custom Eoan amd46 and Disco aarch64 kernels.  Moved some configuration into a seperate conf file.  Basics of a script to monitor upstream repos and trigger builds when upstream changes.  Various other changes and improvements.

diff --git a/ikfs b/ikfs
--- a/ikfs
+++ b/ikfs
@@ -10,7 +10,14 @@ if [ ! "${USER}" == "root" ]; then
   exit 1
 fi
 
+# I found myself getting inotify errors in applications after running this
+#  process a few times.  I assume that something is leaking.  As a workaround I
+#  bumped up the max_user_watches from 8192 to 65535 by running the following:
+#echo fs.inotify.max_user_watches=65535 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system
+
 ikfs_starttime=$(date +%s)
+use_zfs_for_chroot="${use_zfs_for_chroot:-1}"
+zfs_chroot_template_dataset="SSD1/ikfs/chroot-templates"
 os_name="${os_name:-ubuntu}"
 os_cpu="${os_cpu:-$(uname -p)}"
 build_cpu="${build_cpu:-$(uname -p)}"
@@ -20,18 +27,20 @@ kernel_codename="${os_codename}"
 kernel_builders_name="${kernel_builders_name:-${SUDO_USER:-${USER}}} <${kernel_builders_name:-${SUDO_USER:-${USER}}}@$(hostname -f)>"
 
 source "ikfs-common"
+source "ikfs.conf"
 
-tmp_dir="${tmp_dir:-$(mktemp -d /tmp/ikfs.XXXXXXXXXX)}"
+use_gpg_agent=${use_gpg_agent:-0}
+tmp_dir="${tmp_dir:-$(mktemp -d /tmp/build-temp/ikfs.XXXXXXXXXX)}"
 script_dir=$(dirname $(readlink -f "${0}"))
-repository_dir="${script_dir}/repository"
+repository_dir=$(dirname "${script_dir}")"/repository"
 local_patches_dir="${script_dir}/patches"
 chroot_template_dir="${script_dir}/templates/chroot"
 
 # For cross compile using local cpu arch:
-chroot_template_name="ikfs-${os_codename}-${build_cpu}.tgz"
+#chroot_template_name="ikfs-${os_codename}-${build_cpu}.tgz"
 
 # For native compile emulating the target arch using qemu:
-#chroot_template_name="ikfs-${os_codename}-${os_cpu}.tgz"
+chroot_template_name="ikfs-${os_codename}-${os_cpu}.tgz"
 
 chroot_dir="${tmp_dir}/chroot/"
 gpg_signing_uid="shaun@ghanima.net"
@@ -52,10 +61,10 @@ function download_base_rootfs () {
 
 function download_ubuntu_base_rootfs () {
   # For cross compile using local cpu arch:
-  wget -O "${chroot_template_dir}/${chroot_template_name}" "http://cdimage.ubuntu.com/ubuntu-base/releases/${os_codename}/release/ubuntu-base-${os_release}-base-${build_cpu}.tar.gz"
+  #wget -O "${chroot_template_dir}/${chroot_template_name}" "http://cdimage.ubuntu.com/ubuntu-base/releases/${os_codename}/release/ubuntu-base-${os_release}-base-${build_cpu}.tar.gz"
 
   # For native compile emulating the target arch using qemu:
-  #wget -O "${chroot_template_dir}/${chroot_template_name}" "http://cdimage.ubuntu.com/ubuntu-base/releases/${os_codename}/release/ubuntu-base-${os_release}-base-${os_cpu_alt_name}.tar.gz"
+  wget -O "${chroot_template_dir}/${chroot_template_name}" "http://cdimage.ubuntu.com/ubuntu-base/releases/${os_codename}/release/ubuntu-base-${os_release}-base-${os_cpu_alt_name}.tar.gz"
   return $?
 }
 
@@ -79,22 +88,43 @@ function cleanup () {
     if [ -d "${tmp_dir}/chroot/dev" ]; then
       if [ -d "${tmp_dir}/chroot/dev/pts" ]; then
         umount "${tmp_dir}/chroot/dev/pts" 2>/dev/null
+        sleep 5
       fi
       umount "${tmp_dir}/chroot/dev" 2>/dev/null
+      sleep 5
     fi
     if [ -d "${tmp_dir}/chroot/proc" ]; then
       umount "${tmp_dir}/chroot/proc" 2>/dev/null
+      sleep 5
     fi
     if [ -d "${tmp_dir}/chroot/sys" ]; then
       umount "${tmp_dir}/chroot/sys" 2>/dev/null
+      sleep 5
     fi
+  fi
+
+  if [ ! "${zfs_clone}" = "" ]; then
+    echo "Destroying ZFS dataset (cloned from template): '${zfs_clone}'..."
+    zfs destroy "${zfs_clone}"
+  fi
+  if [ ! "${zfs_template_snapshot}" = "" ]; then
+    echo "Destroying ZFS dataset (snapshot of template): '${zfs_template_snapshot}'..."
+    zfs destroy "${zfs_template_snapshot}"
+  fi
+
+  if [ -d "${tmp_dir}/chroot" ]; then
     rm -fr "${tmp_dir}/chroot"
   fi
   rm -fr "${tmp_dir}/"
 }
 
 # Start gpg-agent
-gpg-agent --homedir /home/work/.gnupg --use-standard-socket --daemon --default-cache-ttl 86400
+if [ $use_gpg_agent -gt 0 ]; then
+  gpg-agent --homedir /home/work/.gnupg --use-standard-socket --daemon --default-cache-ttl 86400
+  gpg_pin_entry="ask"
+else
+  gpg_pin_entry="loopback"
+fi
 
 mkdir -p "${chroot_template_dir}/"
 mkdir -p "${chroot_dir}/"
@@ -106,8 +136,50 @@ if [ ! -f "${chroot_template_dir}/${chroot_template_name}" ]; then
   fi
 fi
 
-echo "Extracting base image from template '${chroot_template_name}'..."
-tar -C "${chroot_dir}/" -xzf "${chroot_template_dir}/${chroot_template_name}" || die "Failed to extract base image from template file '${chroot_template_dir}/${chroot_template_name}'."
+if [ $use_zfs_for_chroot -gt 0 ]; then
+  if [ $(zfs list "${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}" | grep -v '^NAME[[:space:]]' | wc -l) -gt 0 ]; then
+    echo "A suitable chroot template ZFS dataset exists for this build: '${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}'."
+  else
+    echo "Creating ZFS chroot template dataset: '${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}'"
+    zfs create -o mountpoint=legacy "${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}"
+  fi
+
+  # We need to make sure that the source ZFS dataset actaully contains content.
+  #  Before we do that though, we need to mount it somewhere.
+  zfs_template_mountpoint=$(zfs list "${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}" | tail -1 | awk '{print $NF}')
+  if [ "${zfs_template_mountpoint}" = "legacy" ] || [ "${zfs_template_mountpoint}" = "-" ]; then
+    zfs_template_mountpoint=$(mktemp -d)
+    echo "ZFS dataset '${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}' will be mounted at '${zfs_template_mountpoint}' temporarially so we can check it's content."
+    zfs set mountpoint=legacy "${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}" || die
+    mount -t zfs "${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}" "${zfs_template_mountpoint}" || die
+  fi
+
+  #TODO: check the source dataset has content
+  if [ -d "${zfs_template_mountpoint}/bin" ] && [ -d "${zfs_template_mountpoint}/var" ]; then
+    echo "Template looks OK.  In thge future though, we problbly want to check harder."
+  else
+    echo "Extracting base image from template '${chroot_template_name}' into the ZFS tempate dataset '${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}'..."
+    pv -f "${chroot_template_dir}/${chroot_template_name}" | tar -C "${zfs_template_mountpoint}/" -xzf - || die "Failed to extract base image from template file '${chroot_template_dir}/${chroot_template_name}'."
+  fi
+  zfs set mountpoint=legacy "${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}" || die
+  # The above should have unmounted the dataset.  This is just a precaution.
+  umount "${zfs_template_mountpoint}" 2>/dev/null
+
+  now=$(date +%s)
+  zfs_template_snapshot="${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}@${now}"
+  zfs_clone="${zfs_chroot_template_dataset}/${os_codename}-${os_cpu}_clone_${now}"
+  echo "Creating a new ZFS snapshot '${zfs_template_snapshot}'..."
+  zfs snapshot "${zfs_template_snapshot}" || die
+  echo "Creating clone of the ZFS template dataset called '${zfs_clone}'..."
+  zfs clone "${zfs_template_snapshot}" "${zfs_clone}" || die
+  echo "Mounting ZFS dataset '${zfs_clone}' at '${chroot_dir}'..."
+  zfs set mountpoint="${chroot_dir}/" "${zfs_clone}" || die
+  #zfs mount "${zfs_clone}"
+else
+  echo "Extracting base image from template '${chroot_template_name}'..."
+  #tar -C "${chroot_dir}/" -xzf "${chroot_template_dir}/${chroot_template_name}" || die "Failed to extract base image from template file '${chroot_template_dir}/${chroot_template_name}'."
+  pv -f "${chroot_template_dir}/${chroot_template_name}" | tar -C "${chroot_dir}/" -xzf - || die "Failed to extract base image from template file '${chroot_template_dir}/${chroot_template_name}'."
+fi
 
 echo "Mounting special filesystems in chroot..."
 mount --bind /dev "${chroot_dir}/dev/" || die "Failed to mount '/dev' within the chroot.  Possible permissions issue?  Did you execute this script with sudo?"
@@ -118,7 +190,7 @@ mkdir -p "${chroot_dir}/tmp/ikfs/" || die "Failed to create a temporary director
 
 if [ -f "${script_dir}/signing_key.pem.gpg" ]; then
   echo "Decrypting and extracting the Linux kernel signing key into the chroot"
-  gpg -a --yes --output ${chroot_dir}/tmp/ikfs/signing_key.pem --decrypt signing_key.pem.gpg
+  gpg --pinentry-mode $gpg_pin_entry -a --yes --output ${chroot_dir}/tmp/ikfs/signing_key.pem --decrypt signing_key.pem.gpg
 else
   echo "No Linux kernel signing key was found.  One will be automatically generated.  If you need a signed kernel and modules for Secure Boot, please review the README.md file for instructions for creating a static signing key."
 fi
@@ -132,9 +204,10 @@ fi
 #  patch the debian/rules file to not disable ZFS or use the slower Qemu method.
 # The slower Qemu method does require the build system has the following
 #  packages installed:
-#  * qemu
+#  * qemu-system-arm
 #  * qemu-user-static
 #  * binfmt-support
+# At the moment, I am unable to get ZFS to compile properly with a cross compile
 
 if [ ! "${build_cpu}" = "${os_cpu}" ]; then
 # TODO: if the chroot is for a different archetecture from the host, we need to
@@ -151,21 +224,10 @@ chroot "${chroot_dir}/" /bin/bash /tmp/ikfs/ikfs-chroot \
   --os-codename="${os_codename}" \
   --kernel-name-suffix="${kernel_name_suffix}" \
   --kernel-builders-name="${kernel_builders_name}" || \
-  die "A process withing the chroot failed.  See the above output for more information."
+  die "A process within the chroot failed.  See the above output for more information."
 
-#TODO: Signing kernel and modules
-# *I think* you might simply be able to drop a signing_key.pem and TODO into the
-#  certs directory in the root of the kernel source tree
-# https://kernel.ubuntu.com/git/ubuntu/ubuntu-disco.git/tree/certs/Makefile line ~58
-# https://kernel.ubuntu.com/git/ubuntu/ubuntu-disco.git/tree/debian/rules.d/2-binary-arch.mk line 56, 106, 287
-# How do I generate some signing keys though and store them securly while still
-#  allowing this process to be automated?
-
-#TODO: We need a patch to
-#  * Change the maintainer name and email address.  We should not give the
-#    impression that Canonical are responsible for our kernels
-#    see: https://manpages.debian.org/jessie/devscripts/dch.1.en.html
-#  * Replace "generic" with "personal" (or something)
+buildtime=$(( $(date +%s) - $ikfs_starttime ))
+echo "Total run time of build process: ${buildtime} seconds"
 
 # Result is in "${chroot_dir}/usr/src/*.deb"
 this_repo_dir="${repository_dir}/${os_name}"
@@ -177,7 +239,7 @@ else
   echo "A helper script for updating ${os_name} repositories doesn't exist yet.  Sorry."
 fi
 
-#cleanup
+cleanup
 
 runtime=$(( $(date +%s) - $ikfs_starttime ))
 echo "Total run time: ${runtime} seconds"
diff --git a/ikfs-chroot-ubuntu b/ikfs-chroot-ubuntu
--- a/ikfs-chroot-ubuntu
+++ b/ikfs-chroot-ubuntu
@@ -3,6 +3,7 @@
 # TODO: build depends only on amd64 and i386: makedumpfile
 
 os_cpu="${os_cpu:-$(uname -p)}"
+build_cpu="${build_cpu:-$(uname -p)}"
 os_codename="${os_codename:-$(lsb_release -c | awk '{print $2}')}"
 os_release="${os_release:-$(lsb_release -r | awk '{print $2}')}"
 build_depends="equivs dkms wget kmod libelf-dev kernel-wedge rsync gawk debhelper git locales dh-systemd libnewt-dev libiberty-dev libdw-dev pkg-config libunwind8-dev liblzma-dev openssl libaudit-dev python-dev libudev-dev autoconf automake uuid-dev binutils-dev libnuma-dev xmlto docbook-utils ghostscript fig2dev bzip2 sharutils asciidoc python-sphinx python-sphinx-rtd-theme dh-autoreconf tzdata python3-distutils python3-lib2to3 ${build_depends}"
@@ -10,7 +11,7 @@ script_dir=$(dirname $(readlink -f "${0}"))
 kernel_git_branch="${kernel_git_branch:-master}"
 kernel_src_dir=/usr/src/linux
 kernel_name_suffix="${kernel_name_suffix:-generic}"
-use_debian_zfs_package=0
+use_debian_zfs_package="${use_debian_zfs_package:-0}"
 
 source "${script_dir}/ikfs-common"
 
@@ -59,12 +60,13 @@ function download_kernel_source () {
   kernel_version_revision=$(echo ${kernel_version} | awk 'BEGIN{FS="."}{print $3}')
   echo "The kernel version of the downloaded source: '${kernel_version}'"
 
-  abi_version=$(basename $(find ./debian.master/abi -maxdepth 1 -mindepth 1 -type d))
+  abi_version=$(cat "debian.master/changelog" | grep '^linux[[:space:]]' | head -1 | awk 'BEGIN{FS="("}{print $2}' | awk 'BEGIN{FS=")"}{print $1}')
   echo "The abi version of the downloaded source: '${abi_version}'"
 
-  prev_abi_version=$(cat "debian.master/changelog" | grep '^linux[[:space:]]' | head -1 | awk 'BEGIN{FS="("}{print $2}' | awk 'BEGIN{FS=")"}{print $1}')
+  prev_abi_version=$(cat "debian.master/changelog" | grep '^linux[[:space:]]' | head -2 | tail -1 | awk 'BEGIN{FS="("}{print $2}' | awk 'BEGIN{FS=")"}{print $1}')
   echo "The abi version of the previous build that this build will be compared to: '${prev_abi_version}'"
 
+  #TODO: I'm no longer confident that the abi versions we're detecting above are quite right
   if [ ! -d "debian.master/abi/${prev_abi_version}" ]; then
     echo "WARN: The previous abi is missing.  Copying the current abi so the checks won't fail."
     avail_abi=$(find "debian.master/abi" -mindepth 1 -maxdepth 1 -type d | sort | head -1)
@@ -75,7 +77,9 @@ function download_kernel_source () {
       cp -r "${avail_abi}" "debian.master/abi/${prev_abi_version}" || return 1
     fi
   fi
+}
 
+function configure_kernel () {
   # Update the changelog to add our own contact details
   echo "kernel_builders_name: ${kernel_builders_name}"
   DEBFULLNAME="${kernel_builders_name}"
@@ -91,7 +95,9 @@ function download_kernel_source () {
     sed -i "s/[[:space:]]generic[[:space:]]/\t${kernel_name_suffix}\t/g" debian.master/d-i/kernel-versions
     sed -i "s/[[:space:]]generic[[:space:]]/ ${kernel_name_suffix} /g" "debian.master/rules.d/${os_cpu_alt_name}.mk"
 
-    #TODO: debian.master/abi/5.2.0-7.8/amd64/*.generic
+    #TODO: debian.master/config/annotations - Then remove the patch
+    #  patches/linux/flavour-all/arch-aarch64/version-disco/0001_LSM_annotations_for_custom_flavour.patch
+
     readarray -t files < <(find "debian.master/abi/${prev_abi_version}/${os_cpu_alt_name}/" -mindepth 1 -maxdepth 1 -type f | grep 'generic')
     for file in "${files[@]}"; do
       new_file=$(echo "${file}" | sed "s/generic/${kernel_name_suffix}/g")
@@ -139,6 +145,30 @@ function download_kernel_source () {
   debian/rules debian/control
   yes | mk-build-deps -i debian/control
   rm debian/control
+
+  # If ca-certificates-java fails to install properly on arm64 chroots on an
+  #  x86_64 host, try the below
+  printf '#!/bin/true' >/var/lib/dpkg/info/ca-certificates-java.postinst
+  dpkg --configure ca-certificates-java
+
+  # For cross compile using local cpu arch:
+  if [ ! "${build_cpu}" = "${os_cpu}" ]; then
+    export CROSS_COMPILE="${os_cpu}-linux-gnu-"
+  fi
+  export $(dpkg-architecture -a${os_cpu_alt_name})
+
+  # From: https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel
+  cd ${kernel_src_dir}
+  chmod a+x debian/rules
+  chmod a+x debian/scripts/*
+  chmod a+x debian/scripts/misc/*
+  fakeroot debian/rules clean
+
+  # I think that "defaultconfigs" does a similar job to "editconfigs" but is
+  #  non-interactive
+  fakeroot debian/rules defaultconfigs
+
+  return 0
 }
 
 function package_version_from_sources () {
@@ -173,7 +203,7 @@ function build_extra_packages () {
     build_extra_package_from_debian "zfs-linux" "experimental/contrib" || \
       build_extra_package_from_debian "zfs-linux" "unstable/contrib" || return 1
   else
-    build_extra_package_from_ubuntu "zfs-linux" "${kernel_codename}/main" || return 1
+    build_extra_package_from_ubuntu "zfs-linux" "eoan/main" || return 1
 
     #TODO: I don't personally need these additional packages but they would also
     #  need to be backported from kernel_codename to os_codename so that they
@@ -184,6 +214,10 @@ function build_extra_packages () {
 
     # If you want to backport any other packages from kernel_codename to
     #  os_codename, here's the place to add them.
+
+    # Canonical are improving grub to support rootfs on ZFS.  Backport their
+    #  latest to Bionic.
+    #build_extra_package_from_ubuntu "grub2" "${kernel_codename}/main" || return 1
   fi
 }
 
@@ -201,7 +235,7 @@ function build_extra_package_from_ubuntu () {
 
   # Extract just the section of the Sources file that relates to the package
   #  we're dealing with
-  cat /tmp/Sources | awk "{ if (/^Package: ${source_package_name}/) { lines=\"\"; section=1 } else if (/^Package: /) {section=0}; if (section>0) {lines=lines\"\n\"\$0}}END{print lines}" \
+  cat /tmp/Sources | awk "{ if (/^Package: ${source_package_name}\$/) { lines=\"\"; section=1 } else if (/^Package: /) {section=0}; if (section>0) {lines=lines\"\n\"\$0}}END{print lines}" \
     >/tmp/Sources_${source_package_name}
 
   # Get the package version
@@ -247,8 +281,15 @@ function build_extra_package_from_ubuntu () {
     # Extract the "orig" tarball, stripping the leading component from the paths
     #  so the root of the source is this directory
     if [[ $file_name == *".orig."* ]]; then
-      echo "Extracting source from '${file_name}'"
-      tar --strip-components=1 -xzf "${file_name}"
+      if [[ $file_name == *".tar.xz"* ]]; then
+        echo "Extracting source from '${file_name}'"
+        tar --strip-components=1 -xJf "${file_name}"
+      elif [[ $file_name == *".tar.gz"* ]]; then
+        echo "Extracting source from '${file_name}'"
+        tar --strip-components=1 -xzf "${file_name}"
+      else
+        echo "Unknown archive format: '${file_name}'."
+      fi
 
     # Extract any additional tarballs
     elif [[ $file_name == *".tar.xz"* ]]; then
@@ -270,7 +311,7 @@ function build_extra_package_from_ubuntu () {
   if [ "${build_cpu}" = "${os_cpu}" ]; then
     debuild -i -us -uc -b
   else
-    debuild -i -us -uc -b -a${os_cpu}
+    debuild -i -us -uc -b -a${os_cpu_alt_name}
   fi
 }
 
@@ -357,8 +398,20 @@ function build_extra_package_from_debian () {
   if [ "${build_cpu}" = "${os_cpu}" ]; then
     debuild -i -us -uc -b
   else
-    debuild -i -us -uc -b -a${os_cpu}
+    debuild -i -us -uc -b -a${os_cpu_alt_name}
   fi
+}
+
+function saved_build_environment {
+  echo "Creating an archive from this build environment, with the various dependencies installed, to speed up future builds..."
+  tar -czf /usr/src/build_environment.tgz \
+    --exclude=/dev \
+    --exclude=/proc \
+    --exclude=/sys \
+    --exclude=/usr/src \
+    --exclude=/etc/resolf.conf \
+    --exclude=/tmp/ikfs
+  return $?
 }
 
 # If we have been sourced from another file, don't run anything that follows
@@ -386,6 +439,13 @@ copy_signing_key || \
 
 configure_kernel || \
   die "[ERROR] Failed to configure the kernel before building.  Cannot continue."
+
+saved_build_environment || \
+  warn "[WARN] Failed to create a copy of the build chroot for use as an updated template"
+# die
+# rm /etc/resolv.conf
+# rm -fr /tmp/ikfs*
+# rm -fr /usr/src/*
 
 build_kernel_package || \
   die "[ERROR] Failed to build the kernel.  Cannot continue."
