Add support for focal kernel (not tested yet).  Add support for RockPi4.

diff --git a/ikfs-chroot-ubuntu b/ikfs-chroot-ubuntu
--- a/ikfs-chroot-ubuntu
+++ b/ikfs-chroot-ubuntu
@@ -65,10 +65,10 @@ function download_kernel_source () {
   kernel_version_revision=$(echo ${kernel_version} | awk 'BEGIN{FS="."}{print $3}')
   echo "The kernel version of the downloaded source: '${kernel_version}'"
 
-  abi_version=$(cat "debian.master/changelog" | grep '^linux[[:space:]]' | head -1 | awk 'BEGIN{FS="("}{print $2}' | awk 'BEGIN{FS=")"}{print $1}')
+  abi_version=$(cat "debian.master/changelog" | egrep '^linux[ |-]' | head -1 | awk 'BEGIN{FS="("}{print $2}' | awk 'BEGIN{FS=")"}{print $1}')
   echo "The abi version of the downloaded source: '${abi_version}'"
 
-  prev_abi_version=$(cat "debian.master/changelog" | grep '^linux[[:space:]]' | head -2 | tail -1 | awk 'BEGIN{FS="("}{print $2}' | awk 'BEGIN{FS=")"}{print $1}')
+  prev_abi_version=$(cat "debian.master/changelog" | egrep '^linux[ |-]' | head -2 | tail -1 | awk 'BEGIN{FS="("}{print $2}' | awk 'BEGIN{FS=")"}{print $1}')
   echo "The abi version of the previous build that this build will be compared to: '${prev_abi_version}'"
 
   #TODO: I'm no longer confident that the abi versions we're detecting above are quite right
@@ -109,8 +109,12 @@ function configure_kernel () {
     readarray -t files < <(find "debian.master/abi/${prev_abi_version}/${os_cpu_alt_name}/" -mindepth 1 -maxdepth 1 -type f | grep 'generic')
     for file in "${files[@]}"; do
       new_file=$(echo "${file}" | sed "s/generic/${kernel_name_suffix}/g")
-      echo "Copying generic abi file '${file}' to '${new_file}'."
-      cp "${file}" "${new_file}"
+      if [ -f "${new_file}" ]; then
+        echo "Not copying generic abi definition file as one already exists for this flavour."
+      else
+        echo "Copying generic abi file '${file}' to '${new_file}'."
+        cp "${file}" "${new_file}"
+      fi
     done
   fi
 
@@ -229,6 +233,10 @@ function build_extra_packages () {
     #  latest to Bionic.
     #build_extra_package_from_ubuntu "grub2" "${kernel_codename}/main" || return 1
   fi
+  #build_extra_package_from_debian "debhelper" "unstable/main" || return 1
+  #build_extra_package_from_debian "libbiod" "unstable/main" || return 1
+  #build_extra_package_from_debian "meson" "unstable/main" || return 1
+  #build_extra_package_from_debian "samba" "unstable/main" || return 1
 }
 
 function build_extra_package_from_ubuntu () {
@@ -414,14 +422,13 @@ function build_extra_package_from_debian () {
 
 function saved_build_environment {
   echo "Creating an archive from this build environment, with the various dependencies installed, to speed up future builds..."
-  cd /
-  tar -czf /usr/src/build_environment.tgz \
-    --exclude=/dev \
-    --exclude=/proc \
-    --exclude=/sys \
-    --exclude=/usr/src \
-    --exclude=/etc/resolf.conf \
-    --exclude=/tmp/ikfs \
+  tar -C / -cvzf /usr/src/build_environment.tgz \
+    --exclude="*/dev/*" \
+    --exclude="*/proc/*" \
+    --exclude="*/sys/*" \
+    --exclude="*/usr/src/*" \
+    --exclude="*/etc/resolf.conf*" \
+    --exclude="*/tmp/ikfs*" \
     .
   return $?
 }
@@ -452,14 +459,14 @@ copy_signing_key || \
 configure_kernel || \
   die "[ERROR] Failed to configure the kernel before building.  Cannot continue."
 
-saved_build_environment || \
-  warn "[WARN] Failed to create a copy of the build chroot for use as an updated template"
-
-echo "Clone this dataset and replace the template."
-die
-rm /etc/resolv.conf
-rm -fr /tmp/ikfs*
-rm -fr /usr/src/*
+#saved_build_environment || \
+#  warn "[WARN] Failed to create a copy of the build chroot for use as an updated template"
+#
+#echo "Clone this dataset and replace the template."
+#die
+#rm /etc/resolv.conf
+#rm -fr /tmp/ikfs*
+#rm -fr /usr/src/*
 
 build_kernel_package || \
   die "[ERROR] Failed to build the kernel.  Cannot continue."
